[servers]
192.168.56.105 ansible_user=erickalvarez apache_package=apache2 php_package=libapache2-mod-php
192.168.56.107 ansible_user=erickalvarez apache_package=apache2 php_package=libapache2-mod-php

[redhat]
192.168.56.108 ansible_user=ealvarez apache_package=httpd php_package=php
